name: macOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    name: macOS CI Check
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [Release]
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        brew update
        brew install cmake
      continue-on-error: true
      
    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        # 使用 macOS 上可用的命令
        cores=$(sysctl -n hw.ncpu)
        cmake --build . --config ${{matrix.build_type}} -j $cores
      continue-on-error: true

    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Map2Curve-macOS-${{ matrix.build_type }}
        path: |
          ${{github.workspace}}/build/bin/*
        retention-days: 5 