name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Linux CI Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release]
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{matrix.build_type}} -j $(nproc)
      continue-on-error: true

    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Map2Curve-Linux-${{ matrix.build_type }}
        path: |
          ${{github.workspace}}/build/bin/*
        retention-days: 5